// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxeventbus.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MxEventBus module

	public static String getLoggerName()
	{
		return (String)Core.getConfiguration().getConstantValue("MxEventBus.LoggerName");
	}
}